# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T04:14:18+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity, HTTPBasic
from fastapi import Path, Query

from models import (
    BranchModel,
    BranchModelResults,
    LandlordAccountingModel,
    LandlordMaintenanceModel,
    LandlordPhotoModelResults,
    LandlordProfitLossModel,
    LandlordRentArrearsModel,
    LandlordSettingsModel,
    LandlordSummaryModel,
    LandlordTenancyModel,
    Object,
    V2CustomerShortNameLandlordLandlordcrmentriesGetResponse,
)

app = MCPProxy(
    contact={'x-twitter': 'agentOSSoftware'},
    title='agentOS Api V2, Customer Login Call Group',
    version='v2-customer',
    servers=[{'url': 'https://live-api.letmc.com'}],
)


@app.get('/v2/customer/{shortName}/branch/branches', tags=['branch_info_management'])
def branch_controller__get_branches(
    short_name: str = Path(..., alias='shortName'), offset: int = ..., count: int = ...
):
    """
    All branches defined for a company
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/branch/branches/{branchID}',
    tags=['branch_info_management'],
)
def get_v2_customer__short_name_branch_branches__branch_i_d(
    short_name: str = Path(..., alias='shortName'),
    branch_i_d: str = Path(..., alias='branchID'),
):
    """
    Get a specific branch given its unique Object ID (OID)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/landlord/accounting', tags=['landlord_account_services']
)
def landlord_controller__get_accounts(
    short_name: str = Path(..., alias='shortName'), token: str = ...
):
    """
    Get the accounting details for the landlord.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/landlord/document', tags=['landlord_account_services']
)
def landlord_controller__get_document(
    short_name: str = Path(..., alias='shortName'),
    token: str = ...,
    i_d: str = Query(..., alias='ID'),
):
    """
    Download a Document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/landlord/inventory',
    tags=['tenancy_information_management'],
)
def landlord_controller__get_invetory_report(
    short_name: str = Path(..., alias='shortName'),
    token: str = ...,
    tenancy_i_d: str = Query(..., alias='tenancyID'),
):
    """
    Generate a Inventory PDF for a tenancy
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/landlord/invoice', tags=['landlord_account_services']
)
def landlord_controller__get_invoice(
    short_name: str = Path(..., alias='shortName'),
    token: str = ...,
    invoice_i_d: str = Query(..., alias='invoiceID'),
):
    """
    Get an invoice pdf belonging to the landlord.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/landlord/landlordcrmentries',
    tags=['landlord_account_services'],
)
def landlord_controller__get_landlord_crm_entries(
    short_name: str = Path(..., alias='shortName'), token: str = ...
):
    """
    Retrieve landlord's CRM ID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/landlord/maintenance', tags=['landlord_account_services']
)
def landlord_controller__get_maintenance_jobs(
    short_name: str = Path(..., alias='shortName'), token: str = ...
):
    """
    Get Active maintenance jobs.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/landlord/profitloss',
    tags=['landlord_account_services', 'tenancy_information_management'],
)
def landlord_controller__get_profit_loss_report(
    short_name: str = Path(..., alias='shortName'), token: str = ...
):
    """
    Generate a Profit and Loss Report
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/landlord/rentarrears',
    tags=['landlord_account_services', 'tenancy_information_management'],
)
def landlord_controller__get_rent_arrears(
    short_name: str = Path(..., alias='shortName'), token: str = ...
):
    """
    Rent Arrears
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/landlord/sas',
    tags=['landlord_account_services', 'tenancy_information_management'],
)
def landlord_controller__get_s_a_s_report(
    short_name: str = Path(..., alias='shortName'),
    token: str = ...,
    year_end: int = Query(..., alias='yearEnd'),
):
    """
    Generate a Self Assessment Tax Report
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/landlord/settings', tags=['landlord_account_services']
)
def landlord_controller__get_settings(
    short_name: str = Path(..., alias='shortName'), token: str = ...
):
    """
    Get contact details of all linked landlords.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/landlord/summary', tags=['landlord_account_services']
)
def landlord_controller__get_summary_details(
    short_name: str = Path(..., alias='shortName'), token: str = ...
):
    """
    Get the summary details for the landlord.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/landlord/tenancy', tags=['tenancy_information_management']
)
def landlord_controller__get_tenancy(
    short_name: str = Path(..., alias='shortName'),
    token: str = ...,
    tenancy_i_d: str = Query(..., alias='tenancyID'),
):
    """
    Get tenancy details.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v2/customer/{shortName}/landlord/tenancy/maintenance/preference',
    tags=['tenancy_information_management', 'landlord_account_services'],
)
def landlord_controller__create_maintenance_preference(
    short_name: str = Path(..., alias='shortName'),
    token: str = ...,
    tenancy_i_d: str = Query(..., alias='tenancyID'),
    name: str = ...,
    notes: str = ...,
):
    """
    Post tenancy maintenance preferences:-
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/landlord/tenancyagreement',
    tags=['tenancy_information_management'],
)
def landlord_controller__get_tenancy_agreement_report(
    short_name: str = Path(..., alias='shortName'),
    token: str = ...,
    tenancy_i_d: str = Query(..., alias='tenancyID'),
):
    """
    Generate a Tenancy Agreement Copy (PDF)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v2/customer/{shortName}/photo/download', tags=['property_photo_handling'])
def photo_controller__get_photo_download(
    short_name: str = Path(..., alias='shortName'),
    token: str = ...,
    photo_i_d: str = Query(..., alias='photoID'),
    width: Optional[int] = None,
    height: Optional[int] = None,
):
    """
    Downloads the photo of a property given the photo ID.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v2/customer/{shortName}/property/{propertyID}/photos',
    tags=['property_photo_handling'],
)
def property_controller__get_properties_photos(
    short_name: str = Path(..., alias='shortName'),
    token: str = ...,
    property_i_d: str = Path(..., alias='propertyID'),
    offset: int = ...,
    count: int = ...,
):
    """
    A collection showing all the photos linked to a specific block, property or room
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/v2/customer/{shortName}/session', tags=['user_authentication_sessions'])
def session_controller__logout(
    short_name: str = Path(..., alias='shortName'), token: str = ...
):
    """
    Logout a customer previously logged in via the Login endpoint.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v2/customer/{shortName}/session', tags=['user_authentication_sessions'])
def session_controller__get_session_info(
    short_name: str = Path(..., alias='shortName'), token: str = ...
):
    """
    Gets information about the currently logged on customer.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/v2/customer/{shortName}/session', tags=['user_authentication_sessions'])
def session_controller__login(
    short_name: str = Path(..., alias='shortName'),
    username: str = ...,
    password: str = ...,
):
    """
    Login as a customer given their username and password.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v2/customer/{shortName}/session/createlandlordlogin',
    tags=['landlord_account_services'],
)
def session_controller__create_landlord_login(
    short_name: str = Path(..., alias='shortName'),
    email: str = ...,
    title: str = ...,
    forename: str = ...,
    surname: str = ...,
    property_address: str = Query(..., alias='propertyAddress'),
    contact_details: str = Query(..., alias='contactDetails'),
    branch_i_d: Optional[str] = Query(None, alias='branchID'),
):
    """
    Send a request to the in-tray to create a landlord login.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v2/customer/{shortName}/session/password', tags=['user_authentication_sessions']
)
def session_controller__change_password(
    short_name: str = Path(..., alias='shortName'),
    token: str = ...,
    old_password: str = Query(..., alias='oldPassword'),
    new_password: str = Query(..., alias='newPassword'),
):
    """
    Change the password of a customer given their existing and new password.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v2/customer/{shortName}/session/resetpassword',
    tags=['user_authentication_sessions'],
)
def session_controller__reset_password(
    short_name: str = Path(..., alias='shortName'), email: str = ...
):
    """
    Reset the customer's password. An email will be sent out to reset.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
