# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T04:14:18+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class BranchModel(BaseModel):
    Address1: Optional[str] = Field(None, description='Branch address line 1.')
    Address2: Optional[str] = Field(None, description='Branch address line 2.')
    Address3: Optional[str] = Field(None, description='Branch address line 3.')
    Address4: Optional[str] = Field(None, description='Branch address line 4.')
    CompanyName: Optional[str] = Field(
        None,
        description='The relevant company name, if not the one specified on the branch then the one on company.',
    )
    County: Optional[str] = Field(None, description='County')
    EMailAddress: Optional[str] = Field(None, description='Branch email address.')
    ETag: Optional[str] = Field(
        None, description='A unique identifier defining the object and change revision.'
    )
    FaxPhone: Optional[str] = Field(None, description='Branch fax phone number.')
    LandPhone: Optional[str] = Field(None, description='Branch land phone number.')
    Name: Optional[str] = Field(None, description='The branch name.')
    OID: Optional[str] = Field(None, description='The unique Object ID (OID).')
    Postcode: Optional[str] = Field(None, description='Branch address postcode.')
    WebAddress: Optional[str] = Field(None, description='Branch web address.')


class BranchModelResults(BaseModel):
    Count: Optional[int] = Field(
        None, description='The total number of results available for all pages'
    )
    Data: Optional[List[BranchModel]] = Field(
        None, description='The resulting data returned from the paged query range'
    )


class KeyValuePairStringString(BaseModel):
    key: Optional[str] = None
    value: Optional[str] = None


class LandlordAccountingEntryModel(BaseModel):
    Amount: Optional[float] = Field(None, description='Amount')
    Date: Optional[datetime] = Field(None, description='Payment Date')
    Description: Optional[str] = Field(None, description='Description.')
    TransactionNumber: Optional[int] = Field(None, description='Transaction Number')


class LandlordAccountingInvoiceModel(BaseModel):
    Date: Optional[datetime] = Field(None, description='Payment Date')
    InvoiceID: Optional[str] = Field(None, description='Transaction Number')
    IsMaintenanceInvoice: Optional[bool] = Field(
        None, description='Does this invoice contain contractor payments?'
    )


class LandlordAccountingModel(BaseModel):
    AccountBalance: Optional[float] = Field(None, description='Account Balance')
    LastPayment: Optional[datetime] = Field(None, description='Last Payment Made')
    PaymentHistory: Optional[List[LandlordAccountingEntryModel]] = Field(
        None, description='Payment History'
    )
    Statements: Optional[List[LandlordAccountingInvoiceModel]] = Field(
        None, description='Statements'
    )


class LandlordChaseNoteModel(BaseModel):
    Date: Optional[datetime] = Field(None, description='Created Date')
    Note: Optional[str] = Field(None, description='Note.')
    NoteType: Optional[str] = Field(None, description='Note Type')
    TenantID: Optional[str] = Field(None, description='Tenant')


class LandlordCrmEntry(BaseModel):
    BranchID: Optional[str] = None
    GlobalReference: Optional[str] = None
    Name: Optional[str] = None
    OID: Optional[str] = None


class LandlordDetailsModel(BaseModel):
    Address: Optional[str] = Field(None, description='Address')
    Email: Optional[str] = Field(None, description='Email')
    GlobalReference: Optional[str] = Field(None, description='User Friendly ID')
    ID: Optional[str] = Field(None, description='ID')
    Mobile: Optional[str] = Field(None, description='Mobile')
    Name: Optional[str] = Field(None, description='Name')
    Phone: Optional[str] = Field(None, description='Phone')


class LandlordLettingsInspectionModel(BaseModel):
    InspectionDate: Optional[datetime] = Field(None, description='InspectionDate')
    Notes: Optional[str] = Field(None, description='Notes')


class LandlordMaintenanceJobNoteModel(BaseModel):
    CreatedAt: Optional[datetime] = Field(None, description='Created At:-')
    NoteContents: Optional[str] = Field(None, description='Note Contents:-')
    OID: Optional[str] = Field(None, description='Job ID:-')


class LandlordMaintenancePreferenceModel(BaseModel):
    Name: Optional[str] = Field(None, description='Name')
    Notes: Optional[str] = Field(None, description='Notes.')
    Type: Optional[str] = Field(None, description='Type')


class PhotoType(Enum):
    Photo = 'Photo'
    Map = 'Map'
    FloorPlan = 'FloorPlan'
    SiteMap = 'SiteMap'
    AerialPhoto = 'AerialPhoto'


class LandlordPhotoModel(BaseModel):
    ETag: Optional[str] = Field(
        None, description='A unique identifier defining the object and change revision.'
    )
    FileName: Optional[str] = Field(None, description='The file name.')
    OID: Optional[str] = Field(None, description='The unique Object ID (OID).')
    PhotoType_1: Optional[PhotoType] = Field(
        None, alias='PhotoType', description='The photo type.'
    )


class LandlordPhotoModelResults(BaseModel):
    Count: Optional[int] = Field(
        None, description='The total number of results available for all pages'
    )
    Data: Optional[List[LandlordPhotoModel]] = Field(
        None, description='The resulting data returned from the paged query range'
    )


class LandlordProfitLossRowModel(BaseModel):
    MonthTotals: Optional[List[KeyValuePairStringString]] = Field(
        None, description='Month Totals'
    )
    NominalCode: Optional[str] = Field(None, description='Nominal Code')
    Title: Optional[str] = Field(None, description='Title of the values.')
    Total: Optional[str] = Field(None, description='Total for all months.')


class LandlordProfitLossSectionModel(BaseModel):
    Rows: Optional[List[LandlordProfitLossRowModel]] = Field(None, description='Rows.')


class LandlordRentOustandingItem(BaseModel):
    DebtDays: Optional[int] = Field(
        None, description='Days since the tenant went into arrears'
    )
    OutstandingRent: Optional[float] = Field(None, description='Outstanding Rent')
    Property: Optional[str] = Field(None, description='Property')
    Tenant: Optional[str] = Field(None, description='Tenant')
    TenantID: Optional[str] = Field(None, description='TenantID')


class LandlordSettingsModel(BaseModel):
    LinkedAccounts: Optional[List[LandlordDetailsModel]] = Field(
        None, description='Linked Accounts'
    )


class LandlordSummaryTenancyModel(BaseModel):
    Bond: Optional[float] = Field(None, description='Bomd')
    BranchID: Optional[str] = Field(None, description='The Tenancy Branch ID')
    Description: Optional[str] = Field(None, description='Description.')
    GlobalReference: Optional[str] = Field(None, description='User Friendly ID')
    ID: Optional[str] = Field(None, description='ID')
    MaintenanceJobs: Optional[int] = Field(None, description='Maintenance Jobs.')
    ManagedRent: Optional[bool] = Field(None, description='State of the tenancy')
    PropertyAddress: Optional[str] = Field(None, description='Display Property Address')
    Rent: Optional[str] = Field(None, description='Rent')
    RentArrears: Optional[float] = Field(None, description='Rent Arrears')
    RentCollected: Optional[float] = Field(None, description='Rent Arrears')
    TenancyProperty: Optional[str] = Field(None, description='Tenancy Property')
    TenancyState: Optional[str] = Field(None, description='State of the tenancy')


class LettingsLandlordDocument(BaseModel):
    FileName: Optional[str] = Field(None, description='File Name')
    FileSize: Optional[int] = Field(None, description='File Size Bytes')
    ID: Optional[str] = Field(None, description='ID')
    MIMEType: Optional[str] = Field(None, description='MIME Type')
    Note: Optional[str] = Field(None, description='Document Note')


class Object(BaseModel):
    pass


class V2CustomerShortNameLandlordLandlordcrmentriesGetResponse(
    RootModel[List[LandlordCrmEntry]]
):
    root: List[LandlordCrmEntry]


class LandlordMaintenanceCertificateModel(BaseModel):
    Due: Optional[datetime] = Field(None, description='Due')
    Files: Optional[List[LettingsLandlordDocument]] = Field(None, description='Files')
    Status: Optional[str] = Field(None, description='Status.')
    Type: Optional[str] = Field(None, description='Type')


class LandlordMaintenanceJobModel(BaseModel):
    AssignedTo: Optional[str] = Field(None, description='AssignedTo')
    ClosedDate: Optional[datetime] = Field(None, description='Job Closed Date:-')
    Description: Optional[str] = Field(None, description='Description')
    MaintenanceNotes: Optional[List[LandlordMaintenanceJobNoteModel]] = None
    Property: Optional[str] = Field(None, description='Property')
    Reported: Optional[datetime] = Field(None, description='Reported')
    Status: Optional[str] = Field(None, description='Status')


class LandlordMaintenanceModel(BaseModel):
    Jobs: Optional[List[LandlordMaintenanceJobModel]] = Field(
        None, description='Maintenance Jobs.'
    )


class LandlordProfitLossModel(BaseModel):
    DirectCosts: Optional[LandlordProfitLossSectionModel] = None
    GrossProfitLoss: Optional[LandlordProfitLossSectionModel] = None
    Income: Optional[LandlordProfitLossSectionModel] = None


class LandlordRentArrearsModel(BaseModel):
    ChaseNotes: Optional[List[LandlordChaseNoteModel]] = Field(
        None, description='Chase Notes'
    )
    RentCollected: Optional[float] = Field(None, description='Rent Collected')
    RentOutstanding: Optional[List[LandlordRentOustandingItem]] = Field(
        None, description='Outstanding Rent'
    )
    TotalRentArrears: Optional[float] = Field(None, description='Rent Arrears')


class LandlordSummaryModel(BaseModel):
    AccountBalance: Optional[float] = Field(None, description='Account Balance')
    LastPayment: Optional[datetime] = Field(None, description='Last Payment Made')
    Tenancies: Optional[List[LandlordSummaryTenancyModel]] = Field(
        None, description='Tenancies'
    )
    TotalRentArrears: Optional[float] = Field(None, description='Rent Arrears')


class LandlordTenancyModel(BaseModel):
    ActualEndDate: Optional[datetime] = Field(None, description='Actual End Date')
    Beds: Optional[int] = Field(None, description='Beds')
    Bond: Optional[float] = Field(None, description='Bond')
    BranchID: Optional[str] = Field(None, description='The tenancy branch ID:-')
    Certificates: Optional[List[LandlordMaintenanceCertificateModel]] = Field(
        None, description='Maintenance Certificates.'
    )
    Documents: Optional[List[LettingsLandlordDocument]] = Field(
        None, description='Tenancy documents:-'
    )
    FixedDate: Optional[datetime] = Field(None, description='Fixed Date')
    GlobalReference: Optional[str] = Field(None, description='User Friendly ID')
    ID: Optional[str] = Field(None, description='ID')
    Inspections: Optional[List[LandlordLettingsInspectionModel]] = Field(
        None, description='Inspections'
    )
    ManagedRent: Optional[bool] = Field(None, description='State of the tenancy')
    Preferences: Optional[List[LandlordMaintenancePreferenceModel]] = Field(
        None, description='Maintenance Preferences.'
    )
    PreviousRentAmount: Optional[float] = Field(
        None, description='Previous Rent Amount'
    )
    PropertyAddress: Optional[str] = Field(None, description='Display Property Address')
    Rent: Optional[str] = Field(None, description='Rent')
    RentAmount: Optional[float] = Field(None, description='Rent Amount')
    StartDate: Optional[datetime] = Field(None, description='Start Date')
    TenancyProperty: Optional[str] = Field(None, description='Tenancy Property')
    TenancyState: Optional[str] = Field(None, description='State of the tenancy')
    Tenants: Optional[List[str]] = Field(None, description='Tenants')
